spring:
  application:
    name: woof-user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/woofdb
    driverClassName: org.postgresql.Driver
    username: woof
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8082
